### ISSUE TITLE
Problems in downloading the dataset

### ISSUE THREAD

**Issue by hclent** [awslabs/gap-text2sql#1]
Hello,

I am going through your setup instructions in the README, and for downloading the dataset there's this command:
`bash data/spider-20190205/generate.sh ./spider`, which is meant to be run from the `rat-sql-gap` dir, I believe, however there is no directory containing this generation script, and I cannot find this script anywhere. 

Please let me know if I am missing something obvious. 

Thanks!

**Comment by Impavidity** [comment]
Hey,

Thank for your interest and we fix the issue in the pull request #2. You can check if it works for you.

**Comment by hclent** [comment]
This solved the problem! Thanks so much! :-)
