### ISSUE TITLE
About max_steps

### ISSUE THREAD

**Issue by yuannjinjie** [awslabs/gap-text2sql#14]
Hello! 
Is max_steps set to 41000? The RAT bert version is set to 81000.
I want to confirm it. Thank you!

**Comment by yuannjinjie** [comment]
And after data preprocess, each word of question, table, and column (that is, some words in the vocabulary) has a prefix. Should this exist? Like Ġthe.

**Comment by JoaoLages** [comment]
I've retrained it and the loss in train is basically 0.00 at step 41000

**Comment by yuannjinjie** [comment]
> I've retrained it and the loss in train is basically 0.00 at step 41000

What's your accuracy in step 41000？

**Comment by JoaoLages** [comment]
Don't recall it, but I was able to obtain the reported 72.72 EXACT score on dev set

**Comment by yuannjinjie** [comment]
> Don't recall it, but I was able to obtain the reported 72.72 EXACT score on dev set

ok, thanks!
