### ISSUE TITLE
I can't find AverageSpanExtractor module :(

### ISSUE THREAD

**Issue by minu4242** [awslabs/gap-text2sql#15]
Hi. @Impavidity @pnpnpn,
I'm referring to your code for my **text-to-SQL** study.
To modify the **GAP encoder** part, I tuned _relogic/tabart-pretraining.py_. 
In order to execute the code, **AverageSpanExtractor** module is needed.
But I can't find this module from _relogic.logickit.modules.span_extractors.average_span_extractor_. 
Is the module missing from github?

Best regard!

**Comment by jjkim0807** [comment]
how did you solve this?

**Comment by jjkim0807** [comment]
How did you solve this?
I cannot find modules in logickit, too.
