### ISSUE TITLE
Cannot access model checkpoint

### ISSUE THREAD

**Issue by romapavelko01** [awslabs/gap-text2sql#31]
Hi, I am trying to learn and test your work and strictly following your instructions, but I cannot quite access model checkpoint from aws s3 bucket; is your project closed now, or checkpoint bucket is not public, or am I having some other connectivity issues?
Running the following command:
`aws s3 cp s3://gap-text2sql-public/checkpoint-artifacts/gap-finetuned-checkpoint logdir/bart_run_1/bs\=12\,lr\=1.0e-04\,bert_lr\=1.0e-05\,end_lr\=0e0\,att\=1/model_checkpoint-00041000`
Getting this error:
`fatal error: An error occurred (403) when calling the HeadObject operation: Forbidden`
Would be grateful for feedback,
Regards

**Comment by Impavidity** [comment]
I think 
```
wget https://gap-text2sql-public.s3.amazonaws.com/checkpoint-artifacts/gap-finetuned-checkpoint
```
works fine to me.

**Comment by romapavelko01** [comment]
Thank you, it really does
